---

- name: test zeromq library role
  hosts: all
  become: true
  vars:
    zeromq_version: 4.1.4
    zeromq_download_url: http://download.zeromq.org/zeromq-{{ zeromq_version }}.tar.gz
    zeromq_prefix: /usr/local  
  tasks:
    - include: 'tasks/main.yml'
