---
- name: install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
    - checkinstall
    - build-essential
    - libtool
    - pkg-config
    - autoconf
    - automake
    - uuid-dev

- name: Download ZeroMQ
  get_url: url={{ zeromq_download_url }} dest=/tmp/zeromq.zip

- name: Unarchive ZeroMQ tarball
  unarchive: >
    copy=no
    src=/tmp/zeromq.zip
    dest=/tmp/zeromq-{{ zeromq_version }}
    creates=/tmp/zeromq-{{ zeromq_version }}/autogen.sh

- name: Autogen script
  shell: ./autogen.sh chdir=/tmp/zeromq-{{ zeromq_version }}

- name: Configure ZeroMQ
  shell: ./configure --prefix={{ zeromq_prefix }} --without-libsodium chdir=/tmp/zeromq-{{ zeromq_version }}

- name: Build ZeroMQ
  shell: make chdir=/tmp/zeromq-{{ zeromq_version }}

- name: Install ZeroMQ
  shell: checkinstall --pkgname=zeromq chdir=/tmp/zeromq-{{ zeromq_version }}

- name: Check installation
  shell: ldconfig && ldconfig -p | grep zmq chdir=/tmp/zeromq-{{ zeromq_version }}
  register: out
  failed_when: "'zmq' not in out.stdout"

